#[tracing::instrument]
pub fn process(_input: &str) -> miette::Result<String> {
	todo!("day 01 - part 1");
}

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_process() -> miette::Result<()> {
		todo!("haven't built test yet");
		let input = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............";
		assert_eq!("14", process(input)?);
		Ok(())
	}
}
